{"name": "Проверка входа с некорректным логином", "status": "failed", "statusDetails": {"message": "AssertionError: assert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 404}\n  \n  Full diff:\n    {...\n  \n  ...Full output truncated (3 lines hidden), use '-vv' to show", "trace": "self = <test_log_in.TestCourierLogin object at 0x000002882101BED0>\n\n    @allure.title('Проверка входа с некорректным логином')\n    @allure.step('В теле запроса указать некорректный логин')\n    def test_incorrect_login_in(self):\n        payload = {\n            \"login\": \"nrutohokage25\",\n            \"password\": \"11234\"}\n    \n        response = requests.post(\"https://qa-scooter.praktikum-services.ru/\" + \"api/v1/courier/login\", data=payload)\n        assert response.status_code == 404\n        data = response.json()\n>       assert data == {\"message\": \"Учетная запись не найдена\"}\nE       AssertionError: assert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Left contains 1 more item:\nE         {'code': 404}\nE         \nE         Full diff:\nE           {...\nE         \nE         ...Full output truncated (3 lines hidden), use '-vv' to show\n\ntests\\test_log_in.py:29: AssertionError"}, "steps": [{"name": "В теле запроса указать некорректный логин", "status": "failed", "statusDetails": {"message": "AssertionError: assert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 404}\n  \n  Full diff:\n    {...\n  \n  ...Full output truncated (3 lines hidden), use '-vv' to show\n", "trace": "  File \"C:\\Users\\Спиридон\\Sprint_7\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Спиридон\\Sprint_7\\tests\\test_log_in.py\", line 29, in test_incorrect_login_in\n    assert data == {\"message\": \"Учетная запись не найдена\"}\n"}, "start": 1714922171663, "stop": 1714922172017}], "start": 1714922171663, "stop": 1714922172017, "uuid": "d35cd3f7-c483-4ce2-81f4-2e3c764d589e", "historyId": "b93f36706091f681daa96f10fa5da1c1", "testCaseId": "b93f36706091f681daa96f10fa5da1c1", "fullName": "tests.test_log_in.TestCourierLogin#test_incorrect_login_in", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_log_in"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "LAPTOP-90R9D1PV"}, {"name": "thread", "value": "22120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_log_in"}]}